# Generated by Django 4.2.3 on 2023-08-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_user', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adresse_domicile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
