# Generated by Django 4.2.3 on 2023-07-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_categorie_remove_article_categorie_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categorie_images/'),
        ),
    ]
