# Generated by Django 4.2.3 on 2023-07-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_categorie_description_categorie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='image',
            new_name='image_categorie',
        ),
    ]
