# Generated by Django 4.2.3 on 2023-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_image_categorie_image_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='image_categorie',
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categorie_images/'),
        ),
    ]
