# Generated by Django 4.2.3 on 2023-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_categorie_image_categorie_categorie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='image',
        ),
        migrations.AddField(
            model_name='categorie',
            name='image_categorie',
            field=models.ImageField(blank=True, null=True, upload_to='categorie_images/'),
        ),
    ]
