# Generated by Django 4.2.3 on 2023-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_article',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='article_images/'),
        ),
    ]
